In [1]:
import numpy as np
x = np.random.randint(low=0, high = 100, size=10)
y = np.random.randint(low=0, high = 100, size = 10)

<h3>Vector/ Unit Vector </h3>
In physics vector quantity has both magnitude and directions. In Machine Learning they are nothing but collection of features that define the sample. So it's also called the feature vector in machine learning. A vector which have a single column $ x = \left(\begin{smallmatrix}a \\ b\end{smallmatrix}\right) $ is called column vector. And which have single row $ x' =  \left(\begin{smallmatrix}a & b\end{smallmatrix}\right)$  is called row vector. </br>
<strong>Unit vector: </strong> A unit vector is a vector of length 1, sometimes also called a direction vector (Jeffreys and Jeffreys 1988). The unit vector $ \hat{v} $ having the same direction as a given (nonzero) vector v is defined by $ \hat{v} = \frac{\vec{v}}{|v|} $




In [11]:
#Finidng Unit vector. There is no built infunction in numpy to find unit vecotr.
# However we can get the unit vector by dividing it's lenght
unit_vector = x / np.linalg.norm(x)
unit_vector

array([0.25771152, 0.4135371 , 0.46747672, 0.49144988, 0.2037719 ,
       0.37757735, 0.07791279, 0.29966456, 0.0719195 , 0.13185241])

<h3>Cosine similarity </h3>
It's the measure of similarity between two non-zero vectors of an inner product space that measures the cosine of the angle between them. Smaller the angle is more similar the vectors are.It's the judgment of orientation and not magnitude. Magnitude is calculated by euclidean distance.</br>
Cosine similarity is generally used as a metric for measuring distance when the magnitude of the vectors does not matter.
\begin{equation}
\theta(A, B) = \frac{\vec{A}.\vec{B}}{\| \mathbf{A} \|\| \mathbf{B} \|}
\end{equation}

In [16]:
# Calculating cosine similarity
# There is no builtin funciton in numpy for calculating that
cosine = np.dot(x, y) / np.linalg.norm(x) * np.linalg.norm(y)
cosine

19928.01326712697

<h3> Euclidean distance</h3>
The Euclidean distance between points p and q is the length of the line segment connecting them ($ \overline{pq} $)

\begin{equation}
d(p,q) = \sqrt{\sum_{i=1}^n (p_i - q_i)^2}
\end{equation}

In [17]:
# Calculating euclidean distance in numpy
euc_dis = np.sqrt(np.sum((x -y) ** 2))
euc_dis

123.18684994754919

<h3>Norms </h3>
<strong>L1 Norms: </strong> Also known as Manhattan Distance or Taxicab norm. L1 Norm is the sum of the magnitudes of the vectors in a space. <br>
<strong>L2 Norms: </strong> Is the most popular norm, also known as the Euclidean norm. It is the shortest distance to go from one point to another. <br>
<strong>L-infinity Norms: </strong> It's the maximum magnitude element of the vector. if x = [1, 3, -19] it's L-infinity norm will be 19.

<h3> Eigenvalue, EigenVector</h3>

When a vector will be subjected to a linear transformation then there are some vector that doesn't change it's directions but change or might not change it's magnitude.That particular vector is called the eigen vector. And the value that the vector value scales into is called eigen value. Eigen vectors are orthogonal to each other. Their dot product is zero.
\begin{equation}
Au = \lambda u
\end{equation}

In [18]:
b = x[:9]
b = b.reshape(3,3)
eigen_value, eigen_vector = np.linalg.eig(b)
print(f"Eigen value {eigen_value}")
print(f"Eigen vector {eigen_vector}")

Eigen value [130.00815863  24.74470513  -2.75286375]
Eigen vector [[ 0.78507588  0.88874187  0.6817796 ]
 [ 0.06125579 -0.05997079 -0.72758536]
 [ 0.61636319 -0.45446825  0.07613221]]


The variance of variable X along direciton U is $ U^T\Sigma U $ If the U is the first eigen vector then variance is the maximum