<h1> 1.1 Statistics </h1>
<p> This notebook focus only the statics requried for Machine Learning. Here we will only use numpy<p>

In [29]:
# importing libraries
import numpy as np
from scipy import stats

<h3> 1.1.1 Mean, Meadian, Mode </h3>

<strong>Mean: </strong> Mean is the average of the sample data. By dividing summation of all sample value by the number of sample value we can get the mean. 
\begin{align}
\bar{x} & = \frac{1}{n}\sum_{i=1}^n x_i\\
\end{align}
<strong>Median: </strong> Median is the midpoint of a sorted dataset. If the dataset has too many outlier then median is more useful than mean. For example, to understand what is the per capita income of a country the median is taken because the rich may be extremely rich which would skew the average and show a different picture than what the average people might experience. In that case, probably, taking the median would give a better insight.

<strong>Mode: </strong> It's the most common value in the dataset. It's usefull to understand the concept of clustering or number of hit of a specific value. For example, a retailer may want to understand the mode of sizes purchased so that he can set stocking labels optimally. Say, store A has a mode of ‘small’ while store B has a mode of ‘XXL’.

For a discrete random variable, the value with highest probability (the location at which the probability mass function has its peak); for a continuous random variable, a location at which the probability density function has a local peak.
<p style="text-align:center"><img src="mean-median-mode.png" /> </p>

In [31]:
# calculating mean median mode.
dataset = (np.random.rand(5,10) * 100).astype(int)
print(dataset)
# Axis 0 will take the mean along y axis, axis 1 will calculate mean along x axis
# keepdims will use the same dimension
print(f"Mean: {np.mean(dataset, axis=0, keepdims=True, dtype=int)}")
print(f"Median: {np.median(dataset, axis=0, keepdims=True)} ")
print(f"Mode: {stats.mode(dataset, axis=0)}")

[[52 69 35 99 21  4 24  6  6 95]
 [62 27  4 75 65 79 77 56 16 57]
 [61 44 35  3 28 91 83 12  7 12]
 [ 7 39 58 29 72 85 84 24 59 48]
 [80 83 90 24 87 79 47 80 22 69]]
Mean: [[52 52 44 46 54 67 63 35 22 56]]
Median: [[61. 44. 35. 29. 65. 79. 77. 24. 16. 57.]] 
Mode: ModeResult(mode=array([[ 7, 27, 35,  3, 21, 79, 24,  6,  6, 12]]), count=array([[1, 1, 2, 1, 1, 2, 1, 1, 1, 1]]))


<h3> 1.1.2 Normal Distribution </h3>

<ul>
    <li>Data creates a bell curve</li>
    <li>The curve is symmetric about the mean</li>
    <li>Most of the data is seen near the mean</li>
    <li>Notation: $ \mathcal{N}(\mu,\,\sigma^{2})\ $ </li>
    <li>Mean = Median = Mode = $ \mu $</li>
    <li> variance = $ \sigma^{2} $. Standard Devation = $ \sigma $ </li>
    <li>PDF:  </li>
</ul>
\begin{align}
P(x) = \frac{1}{\sigma \sqrt {2\pi } }e^-\frac{(x - \mu)^2}{2 \sigma ^2}
\end{align}
<img src="normal-distribution.png" style="max-width:50%"/>
<strong>PDF(Probability Density Function):</strong> 
<ul>
    <li>A random variable is continuous if it can be described by a PDF</li>
    <li>The probability of happening a <strong>super exact</strong> random variable over any distribution is zero. Cause the probability is the area under the curve. And for a exact variable the we will not get a area instead we will get a line. And the area of the line is zero. If we say the probability of getting an exact random variable $ \mu $ is zero. But the probability of getting a random variable between $ \mu - \sigma $ and $ \mu + \sigma $ is 68.27%</li>
</ul>
\begin{align}
\int_{\mu - \sigma}^{\mu + \sigma} \frac{1}{\sigma \sqrt {2\pi } }e^-\frac{(x - \mu)^2}{2 \sigma ^2} dx = 68.27
\end{align}

\begin{align}
\int_{\mu - 2\sigma}^{\mu + 2\sigma} \frac{1}{\sigma \sqrt {2\pi } }e^-\frac{(x - \mu)^2}{2 \sigma ^2} dx = 95.45
\end{align}

\begin{align}
\int_{\mu - 3\sigma}^{\mu + 3\sigma} \frac{1}{\sigma \sqrt {2\pi } }e^-\frac{(x - \mu)^2}{2 \sigma ^2} dx = 99.73
\end{align}

Used resources:
    <ul>
        <li>https://medium.com/technology-nineleaps/basics-of-statistics-for-machine-learning-engineers-bf2887ac716c</li>
    <li></li>
    </ul>