<h1> 1.1 Statistics </h1>
<p> This notebook focus only the statics requried for Machine Learning. Here we will only use numpy<p>

In [2]:
# importing libraries
import numpy as np
from scipy import stats

<h3> 1.1.1 Mean, Meadian, Mode </h3>

<strong>Mean: </strong> Mean is the average of the sample data. By dividing summation of all sample value by the number of sample value we can get the mean. 
\begin{align}
\bar{x} & = \frac{1}{n}\sum_{i=1}^n x_i\\
\end{align}
<strong>Median: </strong> Median is the midpoint of a sorted dataset. If the dataset has too many outlier then median is more useful than mean. For example, to understand what is the per capita income of a country the median is taken because the rich may be extremely rich which would skew the average and show a different picture than what the average people might experience. In that case, probably, taking the median would give a better insight.

<strong>Mode: </strong> It's the most common value in the dataset. It's usefull to understand the concept of clustering or number of hit of a specific value. For example, a retailer may want to understand the mode of sizes purchased so that he can set stocking labels optimally. Say, store A has a mode of ‘small’ while store B has a mode of ‘XXL’.

For a discrete random variable, the value with highest probability (the location at which the probability mass function has its peak); for a continuous random variable, a location at which the probability density function has a local peak.
<p style="text-align:center"><img src="mean-median-mode.png" /> </p>

In [3]:
# calculating mean median mode.
dataset = (np.random.rand(5,10) * 100).astype(int)
print(dataset)
# Axis 0 will take the mean along y axis, axis 1 will calculate mean along x axis
# keepdims will use the same dimension
print(f"Mean: {np.mean(dataset, axis=0, keepdims=True, dtype=int)}")
print(f"Median: {np.median(dataset, axis=0, keepdims=True)} ")
print(f"Mode: {stats.mode(dataset, axis=0)}")

[[55 52 79 72 19 95  9 38 99 29]
 [63 93 59  2 75 24 22 12 44 40]
 [ 6 10 81 84 74 94 27 79 78 11]
 [34  2 39 83 66 79 79 25 40 20]
 [13 19 43 97 90 13 40 59 80 99]]
Mean: [[34 35 60 67 64 61 35 42 68 39]]
Median: [[34. 19. 59. 83. 74. 79. 27. 38. 78. 29.]] 
Mode: ModeResult(mode=array([[ 6,  2, 39,  2, 19, 13,  9, 12, 40, 11]]), count=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]))


<h3> 1.1.2 Normal Distribution </h3>

<ul>
    <li>Data creates a bell curve</li>
    <li>The curve is symmetric about the mean</li>
    <li>Most of the data is seen near the mean</li>
    <li>Notation: $ \mathcal{N}(\mu,\,\sigma^{2})\ $ </li>
    <li>Mean = Median = Mode = $ \mu $</li>
    <li> variance = $ \sigma^{2} $. Standard Devation = $ \sigma $ </li>
    <li>PDF:  </li>
</ul>
\begin{align}
P(x) = \frac{1}{\sigma \sqrt {2\pi } }e^-\frac{(x - \mu)^2}{2 \sigma ^2}
\end{align}
<img src="normal-distribution.png" style="max-width:50%"/>
<strong>PDF(Probability Density Function):</strong> 
<ul>
    <li>A random variable is continuous if it can be described by a PDF</li>
    <li>The probability of happening a <strong>super exact</strong> random variable over any distribution is zero. Cause the probability is the area under the curve. And for a exact variable the we will not get a area instead we will get a line. And the area of the line is zero. If we say the probability of getting an exact random variable $ \mu $ is zero. But the probability of getting a random variable between $ \mu - \sigma $ and $ \mu + \sigma $ is 68.27%</li>
</ul>
\begin{align}
\int_{\mu - \sigma}^{\mu + \sigma} \frac{1}{\sigma \sqrt {2\pi } }e^-\frac{(x - \mu)^2}{2 \sigma ^2} dx = 68.27
\end{align}

\begin{align}
\int_{\mu - 2\sigma}^{\mu + 2\sigma} \frac{1}{\sigma \sqrt {2\pi } }e^-\frac{(x - \mu)^2}{2 \sigma ^2} dx = 95.45
\end{align}

\begin{align}
\int_{\mu - 3\sigma}^{\mu + 3\sigma} \frac{1}{\sigma \sqrt {2\pi } }e^-\frac{(x - \mu)^2}{2 \sigma ^2} dx = 99.73
\end{align}

<h3>1.1.3 Other distributions: </h3>
<strong>Bernoulli distribution:</strong> A random variable distributed according to the Bernoulli distribution can take on two possible values {0, 1}. Let, the probability of a random variable X = 1 is p. So, $ P(X = 1) = p $. 
\begin{equation}
  P(X)=\begin{cases}
    1 - p, & \text{if $X=0$}.\\
    p, & \text{if $X=1$}.
  \end{cases}
\end{equation}
More compactly, $ P(X) = p^x(1-p)^{1-x} $. And this is the PMF(Probability Mass Function) for Bernoulli distribution. One of the example of bernoulli's distribution is Logistic regression.

<strong>Binomial distribution</strong> A sequence of identical bernoulli's event. If X is a Binomial random variable, we denote this $ X ∼ Bin(n, p) $, where p is the probability of success in a given trial and n is total number of trial. Probabililty Mass Function is given by: 
\begin{equation}
    P(X=k) = \binom nk p^k(1-p)^{n-k}
\end{equation}
Mean = $ np $. And variance = $ np(1-p) $

<strong>Poisson distribution:</strong> It deals with arrival of events. It measures probability of the number of events happening over a fixed period of time, given a fixed average rate of occurrence and the event take places independently of the time since the last event. It is parameterized by average arrival rate $ \lambda $. The PMF (Probability Mass Function) is given by:
\begin{equation}
P(X = k) = \frac{e^{-\lambda}\lambda^k}{k!}
\end{equation}
The mean and the variance is $ \lambda $
Example: You see 100 car goes over a road in a day. What is the probability that next day you will see 120 car running on the road. This can be calculated by poission distribuiton. Here $ \lambda = 100  \text{ and }  k = 120 $

<h3> 1.1.4 Standard Deviation </h3>
A measure of the amount of variation or dispersion of a set of values. It is a measure of how spread out numbers are. It's value is the square root of the Variance
\begin{equation}
\sigma = \sqrt{\frac{1}{N-1} \sum_{i=1}^N (x_i - \overline{x})^2}
\end{equation}

In [4]:
# Use numpy to find standard deviation
np.std(dataset, axis=0, keepdims=True)

array([[22.39106965, 33.53445989, 17.5088549 , 33.74374016, 24.17767565,
        35.3327044 , 23.95495773, 23.92153841, 22.64862027, 31.12169661]])

<h3>1.1.5 Correlation</h3>
It measures the strength and direction of the linear relationship between two variables. It's a function of covariance. <strong>What sets them apart is the fact that correlation values are standardized whereas, covariance values are not</strong>. We can obtain the correlation coefficient of two variables by dividing the covariance of these variables by the product of the standard deviations of the same values. When we divide the covariance values by the standard deviation, it essentially scales the value down to a limited range of -1 to +1. This is precisely the range of the correlation values.
\begin{equation}
\rho (x, y) = \frac{Cov(x, y)}{\sigma_x \sigma_y} 
\end{equation}

Used resources:
    <ul>
        <li>https://medium.com/technology-nineleaps/basics-of-statistics-for-machine-learning-engineers-bf2887ac716c</li>
    <li>https://towardsdatascience.com/let-us-understand-the-correlation-matrix-and-covariance-matrix-d42e6b643c22</li>
    </ul>